### ISSUE TITLE
Debian packaging

### ISSUE THREAD

**Issue by RykHawthorn** [jorisroovers/gitlint#51]
Hi,

as explained in the pull request #49 we would like to package gitlint for Debian.

Here is the related "intend to package" (ITP) bug: https://bugs.debian.org/886864

The package was uploaded by @bdrung to the Debian NEW queue:
https://ftp-master.debian.org/new.html (search for gitlint)
Or use: https://ftp-master.debian.org/new/gitlint_0.9.0-1.html

@jorisroovers I would like to use this ticket for a conversation regarding the Debian packaging.

Thanks.

**Comment by RykHawthorn** [comment]
Habemus gitlint Debian package: https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=gitlint

**Comment by bdrung** [comment]
Ubuntu's release schedule: https://wiki.ubuntu.com/BionicBeaver/ReleaseSchedule
The feature freeze (no new features) is on 2018-03-01. Until the Debian Import Freeze (on the same date), the packages from Debian unstable will be automatically synced. gitlint is already synced and in bionic-proposed: https://launchpad.net/ubuntu/+source/gitlint. The binary packages awaiting approval in NEW queue now.

**Comment by RykHawthorn** [comment]
Debian/Ubuntu packaging is working and approved for both distributions.

Currently there is only this bug open:
https://bugs.debian.org/891538

@jorisroovers would be good to have you look into this bug mentioned above. Let me know if we need to change something in the packaging to get this bug fixed. I will prepare a new release package for the latests version.

**Comment by jorisroovers** [comment]
> I also wonder why there's a shell script wrapper there, which is bound
to fail that way instead of just calling the binary with some special
argument....

I agree with this statement from the bug and it's been on my wishlist for a while, but it's unlikely that I'll find time soon to work on this.

> Changing the binary to `python3` works around this issue
I understand that changing the binary to python3 fixes the issue, but I don't think we can do this in gitlint itself as that will break gitlint for other users.

Would need to spend more time on this to brainstorm alternatives, but I think that removing the shell script wrapper stuff all together and going full python for the commit-hook as suggested is the best solution; but again, not something I think I'll have time for soon.

**Comment by RykHawthorn** [comment]
Thanks for your quick reply. I will ignore this bug for the time being then until we go full python3 or find a proper fix. It's not considered release critical.

**Comment by bdrung** [comment]
We should apply the workaround in the Debian package until the shell script is replaced.

**Comment by nickbroon** [comment]
https://tracker.debian.org/pkg/gitlint
The debian package was recently removed from Debian Testing due to automatic failures.

**Comment by nickbroon** [comment]
This can probably be closed, as there is now a debian/ubuntu package available:
https://packages.debian.org/search?keywords=gitlint
