### ISSUE TITLE
Hook compatibility with SourceTree

### ISSUE THREAD

**Issue by wturrell** [jorisroovers/gitlint#7]
When I attempt to commit via SourceTree rather than the CLI, I get:

    git -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree commit -q -F /var/folders/0m/_txwwtzj7sz411brd78rlbv80000gp/T/SourceTreeTemp.uRlEZw 
    .git/hooks/commit-msg: line 11: /dev/tty: Device not configured
    Completed with errors, see above

Any way to fix (or just suppress/ignore) that?

**Comment by jorisroovers** [comment]
We should put a guard there to check if we are using the tty or not.  I'd need to spend some time to replicate. 

What do you think the expected behavior should be though? Just ignoring the commit message all together is probably not the best option. 
If we do have to go down that route we should at least document that gitlint only supports usage through the CLI.
